### ISSUE TITLE
No Class Found : Failed resolution of: Lorg/lwjgl/opengl/GLContext

### ISSUE THREAD

**Issue by cookgreen** [cookgreen/RedAlertAndroid#3]
E/SLICK: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/lwjgl/opengl/GLContext;
        at org.newdawn.slick.opengl.pbuffer.GraphicsFactory.init(GraphicsFactory.java:40)
        at org.newdawn.slick.opengl.pbuffer.GraphicsFactory.createGraphics(GraphicsFactory.java:120)
        at org.newdawn.slick.opengl.pbuffer.GraphicsFactory.getGraphicsForImage(GraphicsFactory.java:91)
        at org.newdawn.slick.Image.getGraphics(Image.java:444)
        at cr0s.javara.render.map.Theater.putTextureInSheet(Theater.java:232)
        at cr0s.javara.render.map.Theater.generateSpriteSheet(Theater.java:88)
        at cr0s.javara.render.map.Theater.<init>(Theater.java:57)
        at cr0s.javara.render.map.TileMap.<init>(TileMap.java:126)
        at cr0s.javara.render.World.<init>(World.java:78)
        at cr0s.javara.main.Main.startNewGame(Main.java:145)
        at cr0s.javara.main.StateLoadingScreen.update(StateLoadingScreen.java:234)
        at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:272)
        at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:517)
        at org.newdawn.slick.GDXGameContainer.render(GDXGameContainer.java:156)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:406)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.lwjgl.opengl.GLContext" on path: DexPathList[[dex file "/data/data/com.android.redalert/code_cache/.overlay/base.apk/classes12.dex", dex file "/data/data/com.android.redalert/code_cache/.overlay/base.apk/classes4.dex", dex file "/data/data/com.android.redalert/code_cache/.overlay/base.apk/classes13.dex", dex file "/data/data/com.android.redalert/code_cache/.overlay/base.apk/classes15.dex", dex file "/data/data/com.android.redalert/code_cache/.overlay/base.apk/classes17.dex", dex file "/data/data/com.android.redalert/code_cache/.overlay/base.apk/classes3.dex", dex file "/data/data/com.android.redalert/code_cache/.overlay/base.apk/classes5.dex", dex file "/data/data/com.android.redalert/code_cache/.overlay/base.apk/classes9.dex", zip file "/data/app/~~Qvk2gCZ0Yv3c6uKML5qDgA==/com.android.redalert-qrk60aC27nnlFSyr1POyJA==/base.apk"],nativeLibraryDirectories=[/data/app/~~Qvk2gCZ0Yv3c6uKML5qDgA==/com.android.redalert-qrk60aC27nnlFSyr1POyJA==/lib/x86, /data/app/~~Qvk2gCZ0Yv3c6uKML5qDgA==/com.android.redalert-qrk60aC27nnlFSyr1POyJA==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.newdawn.slick.opengl.pbuffer.GraphicsFactory.init(GraphicsFactory.java:40) 
        at org.newdawn.slick.opengl.pbuffer.GraphicsFactory.createGraphics(GraphicsFactory.java:120) 
        at org.newdawn.slick.opengl.pbuffer.GraphicsFactory.getGraphicsForImage(GraphicsFactory.java:91) 
        at org.newdawn.slick.Image.getGraphics(Image.java:444) 
        at cr0s.javara.render.map.Theater.putTextureInSheet(Theater.java:232) 
        at cr0s.javara.render.map.Theater.generateSpriteSheet(Theater.java:88) 
        at cr0s.javara.render.map.Theater.<init>(Theater.java:57) 
        at cr0s.javara.render.map.TileMap.<init>(TileMap.java:126) 
        at cr0s.javara.render.World.<init>(World.java:78) 
        at cr0s.javara.main.Main.startNewGame(Main.java:145) 
        at cr0s.javara.main.StateLoadingScreen.update(StateLoadingScreen.java:234) 
        at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:272) 
        at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:517) 
        at org.newdawn.slick.GDXGameContainer.render(GDXGameContainer.java:156) 
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:406) 
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573) 
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272) 
E/SLICK: Failed to render/update
    org.newdawn.slick.SlickException: Game.update() failure - check the game code.
        at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:523)
        at org.newdawn.slick.GDXGameContainer.render(GDXGameContainer.java:156)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:406)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
E/AndroidRuntime: FATAL EXCEPTION: GLThread 779
    Process: com.android.redalert, PID: 18738
    java.lang.RuntimeException: org.newdawn.slick.SlickException: Game.update() failure - check the game code.
        at org.newdawn.slick.GDXGameContainer.render(GDXGameContainer.java:160)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:406)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
     Caused by: org.newdawn.slick.SlickException: Game.update() failure - check the game code.
        at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:523)
        at org.newdawn.slick.GDXGameContainer.render(GDXGameContainer.java:156)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:406) 
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573) 
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272) 
I/Process: Sending signal. PID: 18738 SIG: 9
Disconnected from the target VM, address: 'localhost:5088', transport: 'socket'

**Comment by cookgreen** [comment]
https://github.com/cookgreen/AndroidRA/issues/4
